/* eslint-disable */
/**
 * Generated by Convex
 * Do not manually edit this file
 */

import type { DataModel } from "./server.js";

/**
 * The API for this Convex app.
 *
 * This type includes information about all of the query, mutation, and action
 * functions defined in your Convex app. It also includes information about the
 * document types defined in your schema.
 *
 * This type is used to generate the `api` object used to call these functions
 * from the client.
 */
export type Api = any;

/**
 * The `api` object for this Convex app.
 *
 * Use this object to call your app's Convex API functions from the client.
 */
export declare const api: Api;

/**
 * The `internal` object for this Convex app.
 *
 * Use this object to call your app's internal Convex API functions from the
 * client. These are functions that are not exposed to the public API.
 */
export declare const internal: Api;
