/* eslint-disable */
/**
 * Generated by Convex
 * Do not manually edit this file
 */

import { queryFactory, mutationFactory, actionFactory, httpActionFactory } from "convex/server";

/**
 * Define a query in this Convex app's public API.
 *
 * This function will be allowed to read your Convex database and will be
 * accessible from the client.
 */
export const query = queryFactory;

/**
 * Define a mutation that is part of your app's public API.
 *
 * This function will be allowed to read and write your Convex database and will be
 * accessible from the client.
 */
export const mutation = mutationFactory;

/**
 * Define an action that is part of your app's public API.
 *
 * An action is a function which can execute any JavaScript code, including
 * non-deterministic code and code with side-effects, like calling third-party
 * services. They can also run Convex queries and mutations using the `ctx.runQuery`
 * and `ctx.runMutation` methods. Actions are executed in a separate environment
 * from queries and mutations and may take longer to execute.
 */
export const action = actionFactory;

/**
 * Define an HTTP action that is part of your app's public API.
 *
 * This is an action that can be accessed via an HTTP request instead of the
 * JavaScript `fetch` API. HTTP actions can bypass Convex's caching and
 * optimistic updates, and they can directly set HTTP headers and status codes.
 */
export const httpAction = httpActionFactory;
