/* eslint-disable */
/**
 * Generated by Convex
 * Do not manually edit this file
 */

import type {
  GenericDataModel,
  GenericQueryCtx,
  GenericMutationCtx,
  GenericActionCtx,
  QueryBuilder,
  MutationBuilder,
  ActionBuilder,
  HttpActionBuilder,
} from "convex/server";
import type { GenericId } from "convex/values";

export type TableNames = "projects" | "tasks";

export type Document = any;

export type Id<TableName extends TableNames = TableNames> = GenericId<TableName>;

export interface DataModel extends GenericDataModel {
  projects: {
    document: Document;
    fieldPaths: string;
    indexes: { by_slug: string; by_name: string };
    searchIndexes: any;
    vectorIndexes: any;
  };
  tasks: {
    document: Document;
    fieldPaths: string;
    indexes: { by_project: string; by_status: string; by_project_status: string; by_assignee: string; by_project_position: string };
    searchIndexes: any;
    vectorIndexes: any;
  };
}

export type QueryCtx = GenericQueryCtx<DataModel>;
export type MutationCtx = GenericMutationCtx<DataModel>;
export type ActionCtx = GenericActionCtx<DataModel>;

export declare const query: QueryBuilder<DataModel, "public">;
export declare const mutation: MutationBuilder<DataModel, "public">;
export declare const action: ActionBuilder<DataModel, "public">;
export declare const httpAction: HttpActionBuilder;
